# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nets/protos/anchor_generator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nets.protos import flexible_grid_anchor_generator_pb2 as nets_dot_protos_dot_flexible__grid__anchor__generator__pb2
from nets.protos import grid_anchor_generator_pb2 as nets_dot_protos_dot_grid__anchor__generator__pb2
from nets.protos import multiscale_anchor_generator_pb2 as nets_dot_protos_dot_multiscale__anchor__generator__pb2
from nets.protos import ssd_anchor_generator_pb2 as nets_dot_protos_dot_ssd__anchor__generator__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nets/protos/anchor_generator.proto',
  package='nets.protos',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\"nets/protos/anchor_generator.proto\x12\x0bnets.protos\x1a\x30nets/protos/flexible_grid_anchor_generator.proto\x1a\'nets/protos/grid_anchor_generator.proto\x1a-nets/protos/multiscale_anchor_generator.proto\x1a&nets/protos/ssd_anchor_generator.proto\"\xd2\x02\n\x0f\x41nchorGenerator\x12\x41\n\x15grid_anchor_generator\x18\x01 \x01(\x0b\x32 .nets.protos.GridAnchorGeneratorH\x00\x12?\n\x14ssd_anchor_generator\x18\x02 \x01(\x0b\x32\x1f.nets.protos.SsdAnchorGeneratorH\x00\x12M\n\x1bmultiscale_anchor_generator\x18\x03 \x01(\x0b\x32&.nets.protos.MultiscaleAnchorGeneratorH\x00\x12R\n\x1e\x66lexible_grid_anchor_generator\x18\x04 \x01(\x0b\x32(.nets.protos.FlexibleGridAnchorGeneratorH\x00\x42\x18\n\x16\x61nchor_generator_oneof'
  ,
  dependencies=[nets_dot_protos_dot_flexible__grid__anchor__generator__pb2.DESCRIPTOR,nets_dot_protos_dot_grid__anchor__generator__pb2.DESCRIPTOR,nets_dot_protos_dot_multiscale__anchor__generator__pb2.DESCRIPTOR,nets_dot_protos_dot_ssd__anchor__generator__pb2.DESCRIPTOR,])




_ANCHORGENERATOR = _descriptor.Descriptor(
  name='AnchorGenerator',
  full_name='nets.protos.AnchorGenerator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='grid_anchor_generator', full_name='nets.protos.AnchorGenerator.grid_anchor_generator', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ssd_anchor_generator', full_name='nets.protos.AnchorGenerator.ssd_anchor_generator', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='multiscale_anchor_generator', full_name='nets.protos.AnchorGenerator.multiscale_anchor_generator', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flexible_grid_anchor_generator', full_name='nets.protos.AnchorGenerator.flexible_grid_anchor_generator', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='anchor_generator_oneof', full_name='nets.protos.AnchorGenerator.anchor_generator_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=230,
  serialized_end=568,
)

_ANCHORGENERATOR.fields_by_name['grid_anchor_generator'].message_type = nets_dot_protos_dot_grid__anchor__generator__pb2._GRIDANCHORGENERATOR
_ANCHORGENERATOR.fields_by_name['ssd_anchor_generator'].message_type = nets_dot_protos_dot_ssd__anchor__generator__pb2._SSDANCHORGENERATOR
_ANCHORGENERATOR.fields_by_name['multiscale_anchor_generator'].message_type = nets_dot_protos_dot_multiscale__anchor__generator__pb2._MULTISCALEANCHORGENERATOR
_ANCHORGENERATOR.fields_by_name['flexible_grid_anchor_generator'].message_type = nets_dot_protos_dot_flexible__grid__anchor__generator__pb2._FLEXIBLEGRIDANCHORGENERATOR
_ANCHORGENERATOR.oneofs_by_name['anchor_generator_oneof'].fields.append(
  _ANCHORGENERATOR.fields_by_name['grid_anchor_generator'])
_ANCHORGENERATOR.fields_by_name['grid_anchor_generator'].containing_oneof = _ANCHORGENERATOR.oneofs_by_name['anchor_generator_oneof']
_ANCHORGENERATOR.oneofs_by_name['anchor_generator_oneof'].fields.append(
  _ANCHORGENERATOR.fields_by_name['ssd_anchor_generator'])
_ANCHORGENERATOR.fields_by_name['ssd_anchor_generator'].containing_oneof = _ANCHORGENERATOR.oneofs_by_name['anchor_generator_oneof']
_ANCHORGENERATOR.oneofs_by_name['anchor_generator_oneof'].fields.append(
  _ANCHORGENERATOR.fields_by_name['multiscale_anchor_generator'])
_ANCHORGENERATOR.fields_by_name['multiscale_anchor_generator'].containing_oneof = _ANCHORGENERATOR.oneofs_by_name['anchor_generator_oneof']
_ANCHORGENERATOR.oneofs_by_name['anchor_generator_oneof'].fields.append(
  _ANCHORGENERATOR.fields_by_name['flexible_grid_anchor_generator'])
_ANCHORGENERATOR.fields_by_name['flexible_grid_anchor_generator'].containing_oneof = _ANCHORGENERATOR.oneofs_by_name['anchor_generator_oneof']
DESCRIPTOR.message_types_by_name['AnchorGenerator'] = _ANCHORGENERATOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnchorGenerator = _reflection.GeneratedProtocolMessageType('AnchorGenerator', (_message.Message,), {
  'DESCRIPTOR' : _ANCHORGENERATOR,
  '__module__' : 'nets.protos.anchor_generator_pb2'
  # @@protoc_insertion_point(class_scope:nets.protos.AnchorGenerator)
  })
_sym_db.RegisterMessage(AnchorGenerator)


# @@protoc_insertion_point(module_scope)
