# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nets/protos/matcher.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nets.protos import argmax_matcher_pb2 as nets_dot_protos_dot_argmax__matcher__pb2
from nets.protos import bipartite_matcher_pb2 as nets_dot_protos_dot_bipartite__matcher__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nets/protos/matcher.proto',
  package='nets.protos',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x19nets/protos/matcher.proto\x12\x0bnets.protos\x1a nets/protos/argmax_matcher.proto\x1a#nets/protos/bipartite_matcher.proto\"\x8c\x01\n\x07Matcher\x12\x34\n\x0e\x61rgmax_matcher\x18\x01 \x01(\x0b\x32\x1a.nets.protos.ArgMaxMatcherH\x00\x12:\n\x11\x62ipartite_matcher\x18\x02 \x01(\x0b\x32\x1d.nets.protos.BipartiteMatcherH\x00\x42\x0f\n\rmatcher_oneof'
  ,
  dependencies=[nets_dot_protos_dot_argmax__matcher__pb2.DESCRIPTOR,nets_dot_protos_dot_bipartite__matcher__pb2.DESCRIPTOR,])




_MATCHER = _descriptor.Descriptor(
  name='Matcher',
  full_name='nets.protos.Matcher',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='argmax_matcher', full_name='nets.protos.Matcher.argmax_matcher', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bipartite_matcher', full_name='nets.protos.Matcher.bipartite_matcher', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='matcher_oneof', full_name='nets.protos.Matcher.matcher_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=114,
  serialized_end=254,
)

_MATCHER.fields_by_name['argmax_matcher'].message_type = nets_dot_protos_dot_argmax__matcher__pb2._ARGMAXMATCHER
_MATCHER.fields_by_name['bipartite_matcher'].message_type = nets_dot_protos_dot_bipartite__matcher__pb2._BIPARTITEMATCHER
_MATCHER.oneofs_by_name['matcher_oneof'].fields.append(
  _MATCHER.fields_by_name['argmax_matcher'])
_MATCHER.fields_by_name['argmax_matcher'].containing_oneof = _MATCHER.oneofs_by_name['matcher_oneof']
_MATCHER.oneofs_by_name['matcher_oneof'].fields.append(
  _MATCHER.fields_by_name['bipartite_matcher'])
_MATCHER.fields_by_name['bipartite_matcher'].containing_oneof = _MATCHER.oneofs_by_name['matcher_oneof']
DESCRIPTOR.message_types_by_name['Matcher'] = _MATCHER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Matcher = _reflection.GeneratedProtocolMessageType('Matcher', (_message.Message,), {
  'DESCRIPTOR' : _MATCHER,
  '__module__' : 'nets.protos.matcher_pb2'
  # @@protoc_insertion_point(class_scope:nets.protos.Matcher)
  })
_sym_db.RegisterMessage(Matcher)


# @@protoc_insertion_point(module_scope)
