# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nets/protos/target_assigner.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from nets.protos import box_coder_pb2 as nets_dot_protos_dot_box__coder__pb2
from nets.protos import matcher_pb2 as nets_dot_protos_dot_matcher__pb2
from nets.protos import region_similarity_calculator_pb2 as nets_dot_protos_dot_region__similarity__calculator__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nets/protos/target_assigner.proto',
  package='nets.protos',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n!nets/protos/target_assigner.proto\x12\x0bnets.protos\x1a\x1bnets/protos/box_coder.proto\x1a\x19nets/protos/matcher.proto\x1a.nets/protos/region_similarity_calculator.proto\"\xa9\x01\n\x0eTargetAssigner\x12%\n\x07matcher\x18\x01 \x01(\x0b\x32\x14.nets.protos.Matcher\x12\x46\n\x15similarity_calculator\x18\x02 \x01(\x0b\x32\'.nets.protos.RegionSimilarityCalculator\x12(\n\tbox_coder\x18\x03 \x01(\x0b\x32\x15.nets.protos.BoxCoder'
  ,
  dependencies=[nets_dot_protos_dot_box__coder__pb2.DESCRIPTOR,nets_dot_protos_dot_matcher__pb2.DESCRIPTOR,nets_dot_protos_dot_region__similarity__calculator__pb2.DESCRIPTOR,])




_TARGETASSIGNER = _descriptor.Descriptor(
  name='TargetAssigner',
  full_name='nets.protos.TargetAssigner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='matcher', full_name='nets.protos.TargetAssigner.matcher', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='similarity_calculator', full_name='nets.protos.TargetAssigner.similarity_calculator', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='box_coder', full_name='nets.protos.TargetAssigner.box_coder', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=324,
)

_TARGETASSIGNER.fields_by_name['matcher'].message_type = nets_dot_protos_dot_matcher__pb2._MATCHER
_TARGETASSIGNER.fields_by_name['similarity_calculator'].message_type = nets_dot_protos_dot_region__similarity__calculator__pb2._REGIONSIMILARITYCALCULATOR
_TARGETASSIGNER.fields_by_name['box_coder'].message_type = nets_dot_protos_dot_box__coder__pb2._BOXCODER
DESCRIPTOR.message_types_by_name['TargetAssigner'] = _TARGETASSIGNER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TargetAssigner = _reflection.GeneratedProtocolMessageType('TargetAssigner', (_message.Message,), {
  'DESCRIPTOR' : _TARGETASSIGNER,
  '__module__' : 'nets.protos.target_assigner_pb2'
  # @@protoc_insertion_point(class_scope:nets.protos.TargetAssigner)
  })
_sym_db.RegisterMessage(TargetAssigner)


# @@protoc_insertion_point(module_scope)
